### ISSUE TITLE
Editor Access

### ISSUE THREAD

**Issue by henrik-elburn** [libregraphicsmeeting/htdocs-2019#1]
Hi Ale,

can you grant access so I can work on the site for LGM2019 as editor?

best,

Henrik

**Comment by aoloe** [comment]
hi henrik,

it's done!

just be aware that the master branch is automatically pushed to the lgm server in the 2019/ directory.

also, please only add to the repository the files that are in the theme (and eventually custom plugins) and no CMS files nor any standard plugin.

i think that it would be good to have a chat before you start adding your files to the repository...
