### ISSUE TITLE
Wrong links in the participants list

### ISSUE THREAD

**Issue by Floessie** [libregraphicsmeeting/htdocs-2019#2]
To whom it may concern,

on https://libregraphicsmeeting.org/2019/participants/ the `pixls.us` links refer to `pixlr.com`.

Best,
Flössie

**Comment by aoloe** [comment]
well, normally that list is the result of the https://libregraphicsmeeting.org/2019/registration/

the form exists, the results are there, but i have a hard time understanding how the list is set up.

@soenkez do you know better?

**Comment by Floessie** [comment]
Seems to be fixed. Closing.
